# Generated by Django 3.1.5 on 2021-01-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.post",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="post",
            name="level",
        ),
        migrations.RemoveField(
            model_name="post",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="post",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tree_id",
        ),
    ]
