# Generated by Django 3.1.6 on 2021-02-18 13:11

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		("forum", "0001_initial"),
	]

	operations = [
		migrations.AlterUniqueTogether(
			name="karma",
			unique_together=set(),
		),
	]
