# Generated by Django 3.1.6 on 2021-02-18 13:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		("forum", "0002_auto_20210218_1411"),
	]

	operations = [
		migrations.AlterUniqueTogether(
			name="karma",
			unique_together={("post", "author")},
		),
	]
