# Generated by Django 3.1.5 on 2021-02-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_auto_20210201_2236"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="children",
                to="forum.post",
            ),
        ),
    ]
