# Generated by Django 3.1.6 on 2021-02-18 23:33

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("forum", "0003_auto_20210218_1414"),
	]

	operations = [
		migrations.AlterField(
			model_name="post",
			name="content",
			field=tinymce.models.HTMLField(),
		),
		migrations.AlterField(
			model_name="thread",
			name="categories",
			field=models.ManyToManyField(
				related_name="threads",
				through="forum.Categorisation",
				to="forum.Category",
			),
		),
		migrations.AlterField(
			model_name="thread",
			name="content",
			field=tinymce.models.HTMLField(),
		),
	]
